name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.2

    - name: Set Version Variable for ldflags
      run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Build
      run: make build

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        files: |
          bin/repow-linux-amd64
          bin/repow-linux-arm64
          bin/repow-darwin-amd64
          bin/repow-darwin-arm64
          bin/repow-windows-amd64
